package omnibus

import (
	"fmt"
	"strings"
	"testing"
)

// The fixtures below reproduce the shapes measured on real files:
//
//	authored Go      70% letters, 80% of lines unique, mean line 21
//	authored Markdown 75% letters, 97% unique, mean line 39
//	KiCad schematic  38% letters, 14% unique, 12,167 lines
//	rendered SVG     87% letters, mean line 26,647
//	model catalog    44% letters, 22% unique, 4,424 lines

func authoredGo(n int) string {
	var sb strings.Builder
	sb.WriteString("package tea\n\nimport \"context\"\n\n")
	for i := 0; i < n; i++ {
		fmt.Fprintf(&sb, "// handle%d responds to the message the runtime sends.\n", i)
		fmt.Fprintf(&sb, "func handle%d(ctx context.Context, msg Msg) (Model, Cmd) {\n", i)
		fmt.Fprintf(&sb, "\tif msg == nil {\n\t\treturn nil, waitFor%d\n\t}\n\treturn model%d, nil\n}\n\n", i, i)
	}
	return sb.String()
}

func kicadLike(lines int) string {
	var sb strings.Builder
	sb.WriteString("(kicad_sch (version 20211123) (generator eeschema)\n")
	for i := 0; i < lines; i++ {
		// Short, highly repetitive, heavy on numbers and punctuation.
		fmt.Fprintf(&sb, "    (xy %d.%02d %d.%02d)\n", i%90, i%99, i%70, i%97)
		sb.WriteString("    (stroke (width 0) (type default))\n")
		sb.WriteString("    (fill (type none))\n")
	}
	return sb.String()
}

func renderedSVG() string {
	return `<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080">` +
		`<path d="` + strings.Repeat("M120.5 44.2 L121.9 44.8 C122.4 45.1 123.0 45.9 ", 900) + `"/></svg>`
}

func modelCatalog(entries int) string {
	var sb strings.Builder
	sb.WriteString("{\n  \"models\": [\n")
	for i := 0; i < entries; i++ {
		sb.WriteString("    {\n")
		sb.WriteString("      \"context_window\": 128000,\n")
		sb.WriteString("      \"default_max_tokens\": 8192,\n")
		sb.WriteString("      \"supports_attachments\": true,\n")
		fmt.Fprintf(&sb, "      \"id\": \"model-%d\"\n", i)
		sb.WriteString("    },\n")
	}
	sb.WriteString("  ]\n}\n")
	return sb.String()
}

func TestTriageKeepsAuthoredWork(t *testing.T) {
	cases := map[string]string{
		"tea.go":     authoredGo(60),
		"README.md":  strings.Repeat("Gum provides highly configurable, ready-to-use utilities.\n\n## Usage\n\nRun `gum choose` to pick.\n\n", 40),
		"schema.sql": strings.Repeat("CREATE TABLE events (id INTEGER PRIMARY KEY, name TEXT NOT NULL);\nCREATE INDEX events_name ON events (name);\n", 60),
	}
	for name, text := range cases {
		if reason, _ := TriageText(name, text); reason != "" {
			s := Measure(text)
			t.Errorf("%s was dropped for %q (uniq %.2f, letters %.2f, mean %.0f)",
				name, reason, s.UniqueRatio, s.LetterRatio, s.MeanLine)
		}
	}
}

func TestTriageDropsMachineOutput(t *testing.T) {
	cases := map[string]string{
		"Hardware/rotary/rotary.kicad_sch": kicadLike(4000),
		"test/golden/svg/layout.svg":       renderedSVG(),
		"providers/configs/aihubmix.json":  modelCatalog(900),
		"web/app.min.js":                   "!function(e,t){" + strings.Repeat("var a=1;b(a);", 900) + "}();",
	}
	for name, text := range cases {
		reason, _ := TriageText(name, text)
		if reason == "" {
			s := Measure(text)
			t.Errorf("%s was kept (bytes %d, uniq %.2f, letters %.2f, mean %.0f, longest %d)",
				name, s.Bytes, s.UniqueRatio, s.LetterRatio, s.MeanLine, s.LongestLine)
		}
	}
}

func TestTriageReadsGeneratedMarkers(t *testing.T) {
	// A marker is decisive whatever the file looks like otherwise.
	marked := "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n" + authoredGo(20)
	if reason, _ := TriageText("api.pb.go", marked); reason == "" {
		t.Error("a file that says it is generated should be dropped")
	}
	// The same code without the marker stays.
	if reason, _ := TriageText("api.go", authoredGo(20)); reason != "" {
		t.Errorf("unmarked code was dropped for %q", reason)
	}
	// The words have to be at the head, not buried in prose.
	buried := authoredGo(60) + "\n// Later we should not edit this by hand.\n"
	if reason, _ := TriageText("late.go", buried); reason != "" {
		t.Errorf("a mention deep in a file should not count, got %q", reason)
	}
}

func TestTriageDropsVendoredPaths(t *testing.T) {
	for _, p := range []string{
		"vendor/github.com/pkg/errors/errors.go",
		"node_modules/lodash/lodash.js",
		"third_party/zlib/zlib.h",
		"dist/index.js",
		"web/build/main.css",
		"VENDOR/thing.go",
	} {
		if reason, _ := TriageText(p, authoredGo(10)); reason == "" {
			t.Errorf("%s should have been dropped as vendored", p)
		}
	}
	// A file merely named after one of those words is not vendored.
	for _, p := range []string{"cmd/build.go", "internal/vendor_test.go", "dist.go"} {
		if reason, _ := TriageText(p, authoredGo(10)); reason != "" {
			t.Errorf("%s was dropped for %q", p, reason)
		}
	}
}

func TestTriageIgnoresSmallFiles(t *testing.T) {
	// Statistics need something to measure. A short generated file slips
	// through, which costs a few hundred bytes and is the right trade.
	tiny := "(kicad_sch (version 20211123)\n"
	if reason, _ := TriageText("board.kicad_sch", tiny); reason != "" {
		t.Errorf("a 30-byte file cannot be judged by shape, got %q", reason)
	}
}

func TestMeasure(t *testing.T) {
	s := Measure("alpha\nbeta\nalpha\n\ngamma\n")
	if s.Lines != 6 {
		t.Errorf("Lines = %d, want 6 including the trailing empty", s.Lines)
	}
	if s.UniqueRatio != 0.75 {
		t.Errorf("UniqueRatio = %.2f, want 0.75 (three of four non-blank lines differ)", s.UniqueRatio)
	}
	if s.LongestLine != 5 {
		t.Errorf("LongestLine = %d, want 5", s.LongestLine)
	}
	if s.LetterRatio < 0.7 {
		t.Errorf("LetterRatio = %.2f, want most of it to be letters", s.LetterRatio)
	}
}

func TestTriageReasonsAreCategoriesNotMeasurements(t *testing.T) {
	// Two files of different shapes must land under one heading, or a summary
	// of a large account fills with one line per file.
	a := strings.Repeat(strings.Repeat("x", 420)+"\n", 40)
	b := strings.Repeat(strings.Repeat("y", 530)+"\n", 40)

	ra, da := TriageText("a.txt", a)
	rb, db := TriageText("b.txt", b)
	if ra != rb {
		t.Errorf("categories differ: %q and %q", ra, rb)
	}
	if da == db {
		t.Errorf("details should differ, both were %q", da)
	}
	// The mean counts the trailing newline, so the figures land near the width.
	if !strings.Contains(da, "40") || !strings.Contains(db, "51") {
		t.Errorf("details should carry the measurement, got %q and %q", da, db)
	}
}
