package omnibus

import (
	"path"
	"strings"
	"unicode"
)

// Deciding what belongs in a bundle by extension does not work: every new
// account brings a format nobody listed. These rules look at the file instead.
//
// The thresholds come from measuring real files. Authored Go is 70% letters
// with 80% of its lines unique; a KiCad schematic is 38% letters with 14%
// unique; a rendered SVG averages 26,000 characters a line; a model-catalog
// JSON is 22% unique across 4,400 lines. Those gaps are wide, so the rules sit
// in the middle of them rather than at the edges.

const (
	// A line this long is a serialized blob, not something a person typed.
	maxLineRunes = 5000
	// An average this high means the whole file is machine-written.
	maxMeanLineRunes = 300
	// Below this share of unique lines, a file is a table rather than a text.
	minUniqueLineRatio = 0.35
	// Repetition only means anything once a file is big enough to have shape.
	repetitionFloor = 32 * 1024
	// Below this share of letters, a file is coordinates, hashes, or markup.
	minLetterRatio = 0.25
)

// generatedMarkers are the lines tools write to say a file is theirs. Checked
// against the head of the file, where every convention puts them.
var generatedMarkers = []string{
	"do not edit", "do not modify", "@generated", "code generated by",
	"autogenerated", "auto-generated", "automatically generated",
	"generated by the protocol buffer compiler", "this file was generated",
}

// vendoredDirs hold other people's code, or output built from this repository's
// own code. Either way it is not what the author wrote.
var vendoredDirs = []string{
	"vendor", "node_modules", "third_party", "thirdparty", "bower_components",
	"site-packages", "__pycache__", ".venv", "venv", "dist", "build",
	"target", ".next", ".nuxt", "coverage", "godeps", "_build",
}

// lockNames are dependency graphs a resolver wrote. They are all unique lines
// of ordinary characters, so no statistical rule finds them; only the name does.
var lockNames = map[string]bool{
	"package-lock.json": true, "yarn.lock": true, "pnpm-lock.yaml": true,
	"npm-shrinkwrap.json": true, "composer.lock": true, "gemfile.lock": true,
	"poetry.lock": true, "pdm.lock": true, "uv.lock": true, "cargo.lock": true,
	"go.sum": true, "flake.lock": true, "podfile.lock": true,
	"packages.lock.json": true, "mix.lock": true, "pubspec.lock": true,
}

// licenseNames carry the same text in every repository on earth.
var licenseNames = map[string]bool{
	"license": true, "license.md": true, "license.txt": true,
	"licence": true, "licence.md": true, "licence.txt": true,
	"copying": true, "copying.md": true, "copying.txt": true,
}

// Shape is what a file looks like, measured once and reused by every rule.
type Shape struct {
	Bytes       int
	Lines       int
	MeanLine    float64
	LongestLine int
	UniqueRatio float64
	LetterRatio float64
}

// Measure walks the text once and reports its shape.
func Measure(text string) Shape {
	var s Shape
	s.Bytes = len(text)

	var letters, total int
	for _, r := range text {
		total++
		if unicode.IsLetter(r) {
			letters++
		}
	}
	if total > 0 {
		s.LetterRatio = float64(letters) / float64(total)
	}

	seen := map[string]struct{}{}
	nonBlank, runeTotal := 0, 0
	for _, line := range strings.Split(text, "\n") {
		s.Lines++
		n := len([]rune(line))
		runeTotal += n
		if n > s.LongestLine {
			s.LongestLine = n
		}
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			nonBlank++
			seen[trimmed] = struct{}{}
		}
	}
	if s.Lines > 0 {
		s.MeanLine = float64(runeTotal) / float64(s.Lines)
	}
	if nonBlank > 0 {
		s.UniqueRatio = float64(len(seen)) / float64(nonBlank)
	}
	return s
}

// pathIsVendored reports whether any directory in the path holds code the
// author did not write, or output built from code they did.
func pathIsVendored(rel string) bool {
	for _, part := range strings.Split(path.Dir(rel), "/") {
		for _, dir := range vendoredDirs {
			if strings.EqualFold(part, dir) {
				return true
			}
		}
	}
	return false
}

// hasGeneratedMarker looks for a tool's own claim that it wrote the file.
func hasGeneratedMarker(text string) bool {
	head := text
	if len(head) > 4096 {
		head = head[:4096]
	}
	head = strings.ToLower(head)
	for _, marker := range generatedMarkers {
		if strings.Contains(head, marker) {
			return true
		}
	}
	return false
}

// TriageText decides whether a text file belongs in the bundle. The first
// return is a category, stable enough to group hundreds of files under one
// heading; the second is the measurement that decided this particular file. An
// empty category means keep it.
func TriageText(rel, text string) (category, detail string) {
	if pathIsVendored(rel) {
		return "vendored or built output", path.Dir(rel)
	}
	if hasGeneratedMarker(text) {
		return "marked as generated by the tool that wrote it", ""
	}

	s := Measure(text)
	switch {
	case s.LongestLine > maxLineRunes:
		return "a serialized blob", "one line of " + commas(int64(s.LongestLine)) + " characters"
	case s.MeanLine > maxMeanLineRunes:
		return "machine-written", "lines average " + commas(int64(s.MeanLine)) + " characters"
	case s.Bytes >= repetitionFloor && s.UniqueRatio < minUniqueLineRatio:
		return "a data table", "only " + percent(s.UniqueRatio) + " of its lines differ"
	case s.Bytes >= repetitionFloor && s.LetterRatio < minLetterRatio:
		return "numbers and punctuation", "only " + percent(s.LetterRatio) + " letters"
	}
	return "", ""
}

func percent(f float64) string {
	return commas(int64(f*100+0.5)) + "%"
}
